common:
  img_topic: "/stereo/left/image_raw"
  lid_topic: "/vlp_right/points"
  imu_topic: "/imu/data"
  img_en: 0
  enable_img_sync_in_lio: false
  lidar_en: 1
  ros_driver_bug_fix: false

extrin_calib:
  # Left VLP-16 to IMU, derived from Vehicle2LeftVLP and Vehicle2IMU.
  extrinsic_T: [-0.264623000000, 0.431973000000, 0.240430000000]
  extrinsic_R: [-0.516377000000, -0.702254000000, -0.490096000000,
                0.491997000000, -0.711704000000, 0.501414000000,
                -0.700923000000, 0.017792700000, 0.713015000000]
  # Left VLP-16 to left stereo camera, derived from Vehicle2LeftVLP and Vehicle2Stereo.
  Rcl: [-0.488310263004, 0.716462363120, -0.498231635634,
        0.708917297695, -0.007269188968, -0.705254784718,
        -0.508904924270, -0.697581249635, -0.504358245784]
  Pcl: [-0.171196291220, -0.325925743106, -1.983431693356]

  # Rcl: [-0.488310263004, 0.708917297695, -0.508904924270,
  #       0.716462363120, -0.007269188968, -0.697581249635,
  #       -0.498231635634, -0.705254784718, -0.504358245784]
  # Pcl: [-0.861920664641, -1.263318275667, -1.315516227471]

time_offset:
  lidar_time_offset: 0.0
  imu_time_offset: 0.0
  img_time_offset: 0.0
  exposure_time_init: 0.0

preprocess:
  point_filter_num: 3
  filter_size_surf: 0.1
  lidar_type: 2 # Velodyne
  scan_line: 16
  blind: 1.0

vio:
  max_iterations: 5
  outlier_threshold: 1000 # 78 100 156 #100 200 500 700 infinite
  img_point_cov: 100 # 100 1000
  patch_size: 8
  patch_pyrimid_level: 3
  normal_en: true
  raycast_en: false
  inverse_composition_en: false
  exposure_estimate_en: true
  inv_expo_cov: 0.1

imu:
  imu_en: true
  imu_int_frame: 30
  # acc_cov: 1.0481546278947311e-02
  # gyr_cov: 9.6690835928856730e-03
  # b_acc_cov: 1.8451561389195461e-04
  # b_gyr_cov: 8.2887875865635737e-05
  acc_cov: 0.5 # 0.2
  gyr_cov: 0.3 # 0.5
  b_acc_cov: 0.0001 # 0.1
  b_gyr_cov: 0.0001 # 0.1

lio:
  max_iterations: 5
  dept_err: 0.02
  beam_err: 0.01
  min_eigen_value: 0.0025 # 0.0025
  voxel_size: 0.5
  max_layer: 2
  max_points_num: 50
  layer_init_num: [5, 5, 5, 5, 5]

local_map:
  map_sliding_en: false
  half_map_size: 100
  sliding_thresh: 8

uav:
  imu_rate_odom: false
  gravity_align_en: false

publish:
  dense_map_en: true
  pub_effect_point_en: false
  pub_plane_en: false
  pub_scan_num: 1
  blind_rgb_points: 0.0

evo:
  seq_name: "urban39-pankyo"
  pose_output_en: false

pcd_save:
  pcd_save_en: false
  type: 0 # 0: World Frame, 1: Body Frame;
  colmap_output_en: false # need to set interval = -1
  filter_size_pcd: 0.15
  interval: -1
  # how many LiDAR frames saved in each pcd file;
  # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.

image_save:
  img_save_en: false
  interval: 1
