common:
  img_topic: "/kitti/camera_color_left/image_raw"
  lid_topic: "/kitti/velo/pointcloud"
  imu_topic: "/kitti/oxts/imu"
  img_en: 0
  lidar_en: 1
  ros_driver_bug_fix: false

extrin_calib:
  # lidar->imu
  extrinsic_T: [0.8105439, -0.30705436, 0.80272406]
  extrinsic_R: [9.999976e-01, -7.854027e-04,  2.024406e-03, 
                7.553071e-04,  9.998898e-01,  1.482454e-02, 
                -2.035826e-03, -1.482298e-02,  9.998881e-01]
  # lidar->cam
  Rcl: [ 4.27679909e-04, -9.99967206e-01, -8.08448931e-03,
        -7.21062654e-03,  8.08119513e-03, -9.99941398e-01,
        9.99973895e-01,  4.85949260e-04, -7.20693419e-03]
  Pcl: [ 0.04753334, -0.0555391, -0.28841711]

time_offset:
  # lidar_time_offset: -0.1
  imu_time_offset: 0.0
  img_time_offset: 0.0
  exposure_time_init: 0.0

preprocess:
  point_filter_num: 3
  filter_size_surf: 0.1
  lidar_type: 2 # Velodyne
  scan_line: 64
  scan_rate: 10
  blind: 1.0

vio:
  max_iterations: 5
  outlier_threshold: 1000 # 78 100 156 #100 200 500 700 infinite
  img_point_cov: 100 # 100 1000 
  patch_size: 8
  patch_pyrimid_level: 3
  normal_en: true
  raycast_en: false
  inverse_composition_en: false
  exposure_estimate_en: false
  inv_expo_cov: 0.1

imu:
  imu_en: true
  imu_int_frame: 15
  acc_cov: 0.1 # 0.2
  gyr_cov: 0.1 # 0.5
  b_acc_cov: 0.0001 # 0.1
  b_gyr_cov: 0.0001 # 0.1

lio:
  max_iterations: 5
  dept_err: 0.02
  beam_err: 0.01
  min_eigen_value: 0.0025 # 0.0025
  voxel_size: 0.5
  max_layer: 2
  max_points_num: 50
  layer_init_num: [5, 5, 5, 5, 5]

local_map:  
  map_sliding_en: false
  half_map_size: 100
  sliding_thresh: 8

uav:
  imu_rate_odom: false
  gravity_align_en: false

publish:
  dense_map_en: true
  pub_effect_point_en: false 
  pub_plane_en: false
  pub_scan_num: 1
  blind_rgb_points: 0.0

evo:
  seq_name: "eee_01"
  pose_output_en: true

pcd_save:
  pcd_save_en: false
  type: 0 # 0: World Frame, 1: Body Frame;
  colmap_output_en: false # need to set interval = -1
  filter_size_pcd: 0.15
  interval: -1
  # how many LiDAR frames saved in each pcd file;
  # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.

image_save:
  img_save_en: false
  interval: 1
